application: sensor-analysis
version: 1
runtime: python
api_version: 1

handlers:
- url: /import
  script: importer.py
- url: /getRawData
  script: getRawData.py
- url: /heatgridGen
  script: heatgridGen.py
- url: /heatgrid.xml
  script: heatgridGen.py
- url: /s/heatgrid.xml
  script: heatgridGen.py
- url: /refreshHeatgrid
  script: refreshHeatgrid.py
- url: /cleardata
  script: test_tools/cleardata.py
- url: /createPoints
  script: test_tools/createPoints.py
- url: /insert
  script: test_tools/insert.py
- url: /extract
  script: test_tools/extract.py
- url: /extractAggregate
  script: test_tools/extractAggregate.py
- url: /s
  static_dir: static
- url: /.*
  script: error.py

builtins:
- datastore_admin: on
