application: sensor-analysis
version: 1
runtime: python
api_version: 1

handlers:
- url: /import
  script: importer.py
- url: /getRawData
  script: getRawData.pys
- url: /insert
  script: test_tools/insert.py
- url: /.*
  script: error.py